/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SpellsIndexImport } from './routes/spells/index'
import { Route as SpellsCreateImport } from './routes/spells/create'
import { Route as SpellsSpellIdImport } from './routes/spells/$spellId'

// Create/Update Routes

const SpellsIndexRoute = SpellsIndexImport.update({
  id: '/spells/',
  path: '/spells/',
  getParentRoute: () => rootRoute,
} as any)

const SpellsCreateRoute = SpellsCreateImport.update({
  id: '/spells/create',
  path: '/spells/create',
  getParentRoute: () => rootRoute,
} as any)

const SpellsSpellIdRoute = SpellsSpellIdImport.update({
  id: '/spells/$spellId',
  path: '/spells/$spellId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spells/$spellId': {
      id: '/spells/$spellId'
      path: '/spells/$spellId'
      fullPath: '/spells/$spellId'
      preLoaderRoute: typeof SpellsSpellIdImport
      parentRoute: typeof rootRoute
    }
    '/spells/create': {
      id: '/spells/create'
      path: '/spells/create'
      fullPath: '/spells/create'
      preLoaderRoute: typeof SpellsCreateImport
      parentRoute: typeof rootRoute
    }
    '/spells/': {
      id: '/spells/'
      path: '/spells'
      fullPath: '/spells'
      preLoaderRoute: typeof SpellsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/spells/$spellId': typeof SpellsSpellIdRoute
  '/spells/create': typeof SpellsCreateRoute
  '/spells': typeof SpellsIndexRoute
}

export interface FileRoutesByTo {
  '/spells/$spellId': typeof SpellsSpellIdRoute
  '/spells/create': typeof SpellsCreateRoute
  '/spells': typeof SpellsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/spells/$spellId': typeof SpellsSpellIdRoute
  '/spells/create': typeof SpellsCreateRoute
  '/spells/': typeof SpellsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/spells/$spellId' | '/spells/create' | '/spells'
  fileRoutesByTo: FileRoutesByTo
  to: '/spells/$spellId' | '/spells/create' | '/spells'
  id: '__root__' | '/spells/$spellId' | '/spells/create' | '/spells/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SpellsSpellIdRoute: typeof SpellsSpellIdRoute
  SpellsCreateRoute: typeof SpellsCreateRoute
  SpellsIndexRoute: typeof SpellsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  SpellsSpellIdRoute: SpellsSpellIdRoute,
  SpellsCreateRoute: SpellsCreateRoute,
  SpellsIndexRoute: SpellsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/spells/$spellId",
        "/spells/create",
        "/spells/"
      ]
    },
    "/spells/$spellId": {
      "filePath": "spells/$spellId.tsx"
    },
    "/spells/create": {
      "filePath": "spells/create.tsx"
    },
    "/spells/": {
      "filePath": "spells/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
